{application,ex_keccak,
    [{config_mtime,1756822327},
     {compile_env,
         [{ex_keccak,['Elixir.ExKeccak'],error},
          {rustler_precompiled,[force_build],{ok,[{ex_keccak,true}]}},
          {rustler_precompiled,[force_build,ex_keccak],{ok,true}},
          {rustler_precompiled,[force_build_all],error}]},
     {optional_applications,[rustler]},
     {applications,[kernel,stdlib,elixir,logger,rustler,rustler_precompiled]},
     {description,
         "NIF library for computing Keccak SHA3-256 hashes using tiny-keccak Rust crate."},
     {modules,['Elixir.ExKeccak']},
     {registered,[]},
     {vsn,"0.7.8"}]}.
