{application,mime,
             [{config_mtime,1756822328},
              {compile_env,[{mime,[extensions],error},
                            {mime,[suffixes],error},
                            {mime,[types],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A MIME type module for Elixir"},
              {modules,['Elixir.MIME']},
              {registered,[]},
              {vsn,"2.0.7"},
              {env,[]}]}.
