{application,dotenv,
             [{config_mtime,1756822327},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir]},
              {description,"A port of dotenv to Elixir"},
              {modules,['Elixir.Dotenv','Elixir.Dotenv.Env',
                        'Elixir.Dotenv.Server','Elixir.Dotenv.Supervisor']},
              {registered,[]},
              {vsn,"3.1.0"},
              {mod,{'Elixir.Dotenv',[automatic]}}]}.
