{application,ex_fiskal,
             [{config_mtime,1756822327},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,xmerl,logger,uuid,
                             xmerl_c14n,xml_builder]},
              {description,"Library for creating fiscalized receiptes as per Croatian fiscalization"},
              {modules,['Elixir.ExFiskal',
                        'Elixir.ExFiskal.Enums.PaymentMethod',
                        'Elixir.ExFiskal.Enums.SequenceMark',
                        'Elixir.ExFiskal.PKCS12',
                        'Elixir.ExFiskal.RequestParams',
                        'Elixir.ExFiskal.RequestTemplate',
                        'Elixir.ExFiskal.RequestXML','Elixir.ExFiskal.ZKI']},
              {registered,[]},
              {vsn,"0.1.3"}]}.
